name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-login: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: <your-sonar-project-key>
          sonar-organization: <your-sonar-organization>
          sonar-project-name: <your-sonar-project-name>

      - name: Build and push Docker image
        run: |
          docker build -t your-docker-image:tag .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-docker-image:tag

      - name: Deploy to Kubernetes
        run: kubectl apply -f path/to/kubernetes/yaml/files
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
